apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.microservice.name }}-service
  namespace: {{ .Values.microservice.namespace }}
spec:
  selector:
     app.kubernetes.io/instance: {{ .Values.microservice.name }}
  type: NodePort
  ports:
    - protocol: TCP
      port: {{ .Values.workload.port }}
      targetPort: {{ .Values.workload.port }}
      nodePort: 32000